### ISSUE TITLE
Whoops! Something went wrong. Please check possible error messages above.

### ISSUE THREAD

**Issue by sanderlt** [Fincer/openra-tibsunra2#1]
Hello Comrad!
Something wrong:

CSC OpenRA.Utility.exe
CSC OpenRA.Server.exe
CSC OpenRA.exe

5/7 ***Preparing OpenRA deb package. This takes a while. Please wait.***

For dh_make to find the package name and version, the current directory
needs to be in the format of <package>-<version>.  Alternatively use the
_-p flag using the format <name>_<version> to override it.
The directory name you have specified is invalid!

Your current directory is:
/home/alex/openra-master/openra-bleed-tibsunra2-d8d7c0cfa23517
Perhaps you could try going to directory where the sources are?

Please note that this change is necessary ONLY during the initial
Debianization with dh_make.  When building the package, dpkg-source
will gracefully handle almost any upstream tarball.
            

6/7 ***Compilation process completed. Moving compiled deb package into '/home/alex'***

mv: failed to execute stat for '/home/alex/openra-master/openra-bleed-tibsunra2*.deb': 
No such file or directory

Whoops! Something went wrong. Please check possible error messages above.

**Comment by Fincer** [comment]
Thanks for reporting this one! I'll take a look and get back to you.

**Comment by Fincer** [comment]
Allright, this may have arised as an issue due to late changes to version numbering of compiled openra-tibsunra2 package. As I tested the validity of this issue, I got exactly the same message as you did (Ubuntu 16.04 LTS).

I tested the latest script on OpenSUSE and everything was okay, but it seems that Debian based systems (especially dh-make command) do not like the changes I made to the script.

Basically, the issue exists because _dh_make_ expects numbers to be used in version string, not any letters. Letters were used, and that caused the conflict in Debian based systems, and finally the script failed.

I fixed the issue and uploaded the fix code (needed to change some OpenSUSE/Fedora related strings, too) .

The script should work now.

Thanks again for reporting!

P.S. Please close the issue if the fix works for you, otherwise keep it open.

_Fincer signing out_

**Comment by sanderlt** [comment]
thanks for reply. yep, im using Ubuntu 16.04 LTS. Will try later, and give you feedback. thanks for your work!

**Comment by Fincer** [comment]
You're welcome!
