### ISSUE TITLE
linux-install.sh script attempt to create directory fails

### ISSUE THREAD

**Issue by WolfFinster** [Fincer/openra-tibsunra2#13]
I have run the script under Mint 17.3 and OpenSUSE Tumbleweed 42.1 and am getting the same error. The script attempts to create a directory and fails. In fact when I manually create that directory and run the script, the script will delete the directory:

```Part 2 (Red Alert 2 mod files):

Cloning into '/home/<user>/openra-master/ra2'...
remote: Counting objects: 3612, done.
remote: Total 3612 (delta 0), reused 0 (delta 0), pack-reused 3612
Receiving objects: 100% (3612/3612), 4.92 MiB | 2.11 MiB/s, done.
Resolving deltas: 100% (2330/2330), done.
mkdir: cannot create directory ‘/home/<user>/openra-master/openra-bleed-tibsunra2/mods/ra2/bits/vehicles’: No such file or directory

Whoops! Something went wrong. Please check possible error messages above.

**Comment by Fincer** [comment]
The script is outdated due to changes to the OpenRA codebase. The script relies on modchooser functionality which was removed recently from OpenRA. There may be other outdated parts as well.

I am aware of these issues. Sadly, I don't have enough time to fix them now. I check if I have time in the near future but I can hardly promise anything.

**Comment by muleyyy** [comment]
is there a work around for this? if the issue means a change in the script that might be doable

**Comment by Fincer** [comment]
I have not tested this script for quite some time, and many parts are deprecated I guess.

The script should be re-worked step by step for achieving compatibility with the current OpenRA/ra2 release. However, I am busy with other things and unfortunately lack time to do that. Feel free to fork the script and make a pull request. ;)

**Comment by MitusM** [comment]
I have run the script under Ubuntu 18.04 and am I getting the same error. 

Cloning into «/home/misha/openra-master/ra2»…
remote: Enumerating objects: 152, done.
remote: Counting objects: 100% (152/152), done.
remote: Compressing objects: 100% (107/107), done.
remote: Total 5426 (delta 58), reused 90 (delta 42), pack-reused 5274
Receiving objects: 100% (5426/5426), 7.86 MiB | 3.24 MiB/s, done.
Resolving deltas: 100% (3480/3480), done.
mkdir: cannot create directory «/home/misha/openra-master/openra-bleed-tibsunra2/mods/ra2/bits/vehicles»: No such file or directory
find: ‘/home/misha/.gvfs’: Отказано в доступе

Whoops! Something went wrong. Please check possible error messages above.

**Comment by Fincer** [comment]
@MitusM Sadly, the script is outdated, and I don't really want to rewrite/re-structure it for newer OpenRA releases & compherensively test it on multiple platforms since I don't much play OpenRA nowadays.

The game code changed couple of years ago which inevitably led to the broken script. I added a note to README 2 years ago so people could avoid attempting to run the script with the recent OpenRA releases:

`NOTE! This script is currently incompatible with the current OpenRA & OpenRA/ra2 release`

As this is an open source project, I'd be happy to see someone to fork & rewrite the script.
