### ISSUE TITLE
Error when patching files

### ISSUE THREAD

**Issue by TechnoSparks** [Fincer/openra-tibsunra2#8]
The script fails to patch the files and this applies both when I accepted to use hotfixes and otherwise.

## Error Output
**If hotfixes aren't chosen**
```
patching file mods/all/mod.yaml
patching file mods/ra2/mod.yaml
patching file utility.cmd
patching file Makefile
Hunk #5 FAILED at 379.
1 out of 5 hunks FAILED -- saving rejects to file Makefile.rej
```
Contents of Makefile.rej
```
--- Makefile
+++ Makefile
@@ -379,6 +394,8 @@
 	@$(INSTALL_DIR) "$(DATA_INSTALL_DIR)/mods"
 	@$(CP_R) mods/common "$(DATA_INSTALL_DIR)/mods/"
 	@$(INSTALL_PROGRAM) $(mod_common_TARGET) "$(DATA_INSTALL_DIR)/mods/common"
+	@$(CP_R) mods/ra2 "$(DATA_INSTALL_DIR)/mods/"
+	@$(INSTALL_PROGRAM) $(mod_ra2_TARGET) "$(DATA_INSTALL_DIR)/mods/ra2"
 	@$(CP_R) mods/cnc "$(DATA_INSTALL_DIR)/mods/"
 	@$(INSTALL_PROGRAM) $(mod_cnc_TARGET) "$(DATA_INSTALL_DIR)/mods/cnc"
 	@$(CP_R) mods/d2k "$(DATA_INSTALL_DIR)/mods/"
```

**If hotfixes are chosen**
```
patching file Makefile
Hunk #1 succeeded at 389 (offset 1 line).
patching file Makefile
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file Makefile.rej
```
Contents of Makefile.rej
```
--- Makefile
+++ Makefile
@@ -427,9 +427,9 @@
 	@echo 'cd "$(gameinstalldir)"' >> openra
 # Note: this relies on the non-standard -f flag implemented by gnu readlink
 ifeq ($(DEBUG), $(filter $(DEBUG),false no n off 0))
-	@echo 'mono OpenRA.Game.exe Engine.LaunchPath="$(readlink -f $0)" "$$@"' >> openra
+	@echo 'mono OpenRA.Game.exe Engine.LaunchPath="$$(readlink -f $$0)" "$$@"' >> openra
 else
-	@echo 'mono --debug OpenRA.Game.exe Engine.LaunchPath="$(readlink -f $0)" "$$@"' >> openra
+	@echo 'mono --debug OpenRA.Game.exe Engine.LaunchPath="$$(readlink -f $$0)" "$$@"' >> openra
 endif
 	@echo 'if [ $$? != 0 -a $$? != 1 ]' >> openra
 	@echo 'then' >> openra
```

## How to reproduce
1. Run the installer script
2. Follow the instructions
3. Error occurs at action 3 out of 7

## Modifications?
I modified the script to not git clone the repos again and again. This is because I have wasted a total of 300MB of my limited mobile internet quota. The modification only makes the script to copy an already downloaded repo folder to "openra-master". Basically, integral parts of the script remain untouched

## Other attempts
I attempted to compile the source without patching. Of course, the game compiled but there will be no RA2 mod.

## System information
Ubuntu Gnome 16.10 64-bit
Dependencies all satisfied

**Comment by Fincer** [comment]
I suspect this is just another out-dated patch issue. Thank you for the detailed report. I'll take a look on this issue in the following weekend (sorry, I'll be busy before that).

## About the current hotfixes

The current hotfixes have been included because they "fix" some issues which cause Red Alert & Tiberian Sun mods not to be included in the compiled OpenRA package due to recent changes in the OpenRA code. There is something more, too. Please see details below. 

These hotfixes are temporary and will be removed some day in the future. Meanwhile, though the installer indicates that hotfixes are usually optional (you can actually select whether to use them or not), the current hotfixes are actually somewhat a necessity.

## Current hotfixes explained

**hotfix-makefile-enable-ra-and-ts** = Enable RA & TS mods contents in Linux builds

**hotfix-makefile-readlink** = Fix an issue which causes misconfigured scripts to be added in openra executable script (you can't start the game without the changes this hotfix patch does)

**hotfix-ra2-withexitoverlay-revert** = I had some compilation issues with some recent changes in _/OpenRA.Mods.RA2/Traits/Render/WithExitOverlay.cs_ file. As the previous version of the file compiled without any issues, I made a quick hotfix to revert those error prone codes. Not a good fix, but better than having a total failure in compilation process.

**Comment by TechnoSparks** [comment]
Thank you for the explanation, now those hotfixes make sense!

Take your time and do changes when you feel comfortable to. This is a voluntary contribution effort made by you, and I wholeheartedly understand that you are not entitled to fix this in an urgent manner :smile:

I wish I can contribute and help myself, but I don't have knowledge on the matter.

Thank you again

**Comment by Fincer** [comment]
Yup :)

I took a look into the issue and well, _hotfix-makefile-readlink.patch_ was outdated by [this](https://github.com/OpenRA/OpenRA/commit/f6c607c4612cc01f8a418a5dfc23b9819eb150cb) OpenRA commit. So, the hotfix is removed now.

Another issue was with _hotfix-makefile-enable-ra-and-ts.patch_. Red Alert has been enabled by the same OpenRA official commit (link above), so I removed RA part and kept just Tiberian Sun (so the hotfix is called now _hotfix-makefile-enable-ts.patch_).

For meanwhile, I recommend to enable hotfixes when the script asks you what to do with them. If you don't do it...well, RA2 compilation may fail and you can't play Tiberian Sun.

I still need test the Windows compilation script.

**Comment by Fincer** [comment]
Windows version of the script should be okay (tested on Win7).

The openra-tibsunra2 script is now updated. Thanks again for reporting the issue! 

Closing the issue now.

**Comment by TechnoSparks** [comment]
Sorry for the late response. I thought I have already submitted a newer comment..

After the commits in regard to this issue has been pushed, I have pulled the newer changes and gone through a newer attempt and everything went as planned!

Thank you for creating a very helpful automator script, especially for a mod based on a game that built my childhood! :)

// Off-topic
Now I will enjoy practising with still in-development AI, before the mod went official in original OpenRA. Since I saw a small competitive scene with OpenRA, I hope there would also be some too for RA2!

**Comment by Fincer** [comment]
No probs! It's always nice to help people with this stuff.

The structure of the script is quite "bad" as someone stated in a Reddit conversation. I may rewrite the script, but not sure if there's a point to do that because...

...once OpenRA/ra2 gets merged with the main OpenRA/OpenRA repository, the only thing this script can still do is to enable ra2 mod in OpenRA game (I assume TS has already been enabled for players by then). When this happens...I have no idea. TS mod likely gets out this year and RA2 may follow in 2018/2019.

Anyway. I feel it's pointless to put more effort for a simple task (re-writing the script) because the aforementioned will likely happen in some day. For the meanwhile, this script helps people but it isn't meant to exist there forever. 

The whole reason I wrote the script is because 

1) OpenRA devs haven't merged OpenRA/OpenRA + OpenRA/ra2 repositories yet
2) there is no another easy way to enable TS/RA2 mods in OpenRA yet

I assume that most average players don't want to put their hands on compilation processes though the official installation instruction in OpenRA wiki suggest just that. (In other words: most players give up before _even reading_ further about compilation steps). I assume players don't want to understand what happens under the hood. Instead, they want... well, just want to play, nothing more. And there's nothing wrong in that. Personally, I know that kind of people in my real life.

To be honest: It feels like devs don't want people to play TS/RA2 yet (I guess it's because so many features haven't still be implemented so they see the mods are not ready for public yet). If that's true, I must say: I disagree. Hopefully that policy will change.

Getting TS/RA2 mods available for larger group of people may even help in reporting bugs and thus improve the development of these mods in OpenRA (or at least it has potential for that). People who want to play these mods even if they're not ready...people are likely aware of possible bugs and lack of features, and may agree that the mods are unfinished.

Hopefully you enjoy RA2 mod as it is. AI stuff may improve in the future but I don't know more about that.
